spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MESS?serverTimezone=Asia/Seoul
    username: mess
    password: mess

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        sql: debug